name: CMake
'on':
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: Extra Resolve Options
        required: false
  push:
    branches:
    - master
  pull_request: null
env:
  EXTRA_RESOLVE_OPTIONS: ${{ github.event.inputs.resolve_options }}
jobs:
  docker_builds:
    container:
      image: ${{ matrix.config.container }}
      options: --user 0:0
      volumes:
      - /home/buildbot/.ssh:/root/.ssh
    name: ${{ matrix.config.name }}
    runs-on:
    - self-hosted
    - docker
    - builder
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: CMake Cleanup
      run: cmake -E remove_directory build
    - name: CMake Setup
      run: cmake -E make_directory build
    - name: CMake Configure
      run: cmake ../ -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DSTEINWURF_RESOLVE_OPTIONS="--git_protocol=git@
        $EXTRA_RESOLVE_OPTIONS"
      working-directory: ${{github.workspace}}/build
    - name: CMake Build
      run: cmake --build .
      working-directory: ${{github.workspace}}/build
    strategy:
      fail-fast: false
      matrix:
        config:
        - container: ghcr.io/steinwurf/python-bindings:latest
          name: Cmake 3.16.3 (GCC)
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
