name: C++ make-specs
on:
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: "Extra Resolve Options"
        required: false
  schedule:
    - cron: "0 1 * * *" # 3 AM CET
  push:
  pull_request:
env:
  EXTRA_RESOLVE_OPTIONS: ${{ github.event.inputs.resolve_options }}
jobs:
  docker_builds:
    strategy:
      fail-fast: false
      matrix:
        config:
          - container: conanio/gcc54
            cxx_mkspec: --cxx_mkspec=cxx_gxx54_x64
            name: GCC 5.4
          - container: conanio/gcc9
            cxx_mkspec: --cxx_mkspec=cxx_gxx92_x64
            name: GCC 9.2
          - container: conanio/clang39
            name: Clang 3.9
            cxx_mkspec: --cxx_mkspec=cxx_clang39_x64
          - container: conanio/clang10
            name: Clang 10
    runs-on: [self-hosted, docker]
    name: ${{ matrix.config.name }}
    container:
      image: ${{ matrix.config.container }}
      options: --user 0:0
      volumes:
        - /home/buildbot/.ssh:/root/.ssh
    steps:
      - name: Install SSH client
        run: apt update && apt -y install openssh-client
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Waf Configure
        run: python3 waf configure --git_protocol=git@ ${{ matrix.config.cxx_mkspec }} $EXTRA_RESOLVE_OPTIONS
      - name: Waf Build
        run: |
          echo "::add-matcher::.github/gcc-problem-matcher.json"
          python3 waf
      - name: Waf Test
        run: python3 waf --run_tests
  # Build performed on runner using make specs
  cxx_mkspec:
    strategy:
      fail-fast: false
      matrix:
        include:
          - cxx_mkspec: cxx_msvc16_x64
            name: MSVC 16 64-bit
            # On Windows Python3 is just python
            # See https://stackoverflow.com/a/48356397/246759
            python: python
          - cxx_mkspec: cxx_clang70_x64
            name: Clang 7.0 64-Bit
            python: python3
          - cxx_mkspec: cxx_gxx83_x64
            name: GCC 8.3 64-Bit
            python: python
    runs-on: [self-hosted, "${{ matrix.cxx_mkspec }}"]
    name: ${{ matrix.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        env:
          GIT_SSH_COMMAND: "${{ runner.os != 'Linux' && 'ssh' || 'ssh -i /home/buildbot/.ssh/id_ed25519 -o IdentitiesOnly=yes' }}"
        run: ${{ matrix.python }} waf configure --git_protocol=git@ --cxx_mkspec=${{ matrix.cxx_mkspec }} $EXTRA_RESOLVE_OPTIONS
      - name: Build
        run: |
          echo "::add-matcher::.github/gcc-problem-matcher.json"
          ${{ matrix.python }} waf build
      - name: Test
        run: ${{ matrix.python }} waf build --run_tests
