jobs:
  Linux:
    container:
      image: ${{ matrix.config.container }}
      options: --user 0:0
      volumes:
      - /home/buildbot/.ssh:/root/.ssh
    name: ${{ matrix.config.name }}
    runs-on:
    - self-hosted
    - docker
    - builder
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    - env:
        EXTRA_RESOLVE_OPTIONS: ${{ inputs.extra_resolve_options }}
      name: Waf Configure
      run: python3 waf configure --git_protocol=git@ ${{ env.EXTRA_RESOLVE_OPTIONS
        }}
    - name: Waf Build
      run: 'echo "::add-matcher::.github/gcc-problem-matcher.json"

        python3 waf

        '
    - name: Waf Test
      run: python3 waf --run_tests
    strategy:
      fail-fast: false
      matrix:
        config:
        - container: ghcr.io/steinwurf/python-bindings:latest
          name: GCC 9.3
name: Linux Waf
'on':
  pull_request: null
  push:
    branches:
    - master
  schedule:
  - cron: 0 1 * * *
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: Extra Resolve Options
        required: false
