name: No Assertions
on:
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: "Extra Resolve Options"
        required: false
  schedule:
    - cron: "0 1 * * *" # 3 AM CET
  push:
  pull_request:
env:
  EXTRA_RESOLVE_OPTIONS: ${{ github.event.inputs.extra_resolve_options }}
jobs:
  ndebug:
    name: No Assertions
    runs-on: [self-hosted, docker, builder]
    container:
      image: ghcr.io/steinwurf/python-bindings:latest
      options: --user 0:0
      volumes:
        - /home/buildbot/.ssh:/root/.ssh
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        env:
          EXTRA_RESOLVE_OPTIONS: ${{ inputs.extra_resolve_options }}
          GIT_SSH_COMMAND: ssh -i /home/buildbot/.ssh/id_ed25519 -o IdentitiesOnly=yes
        run: python3 waf configure --cxx_nodebug --git_protocol=git@ ${{ env.EXTRA_RESOLVE_OPTIONS }}
      - name: Build
        run: |
          echo "::add-matcher::.github/gcc-problem-matcher.json"
          python3 waf
      - name: Test
        run: python3 waf --run_tests

# Cancel previous in-progress when pushing: https://stackoverflow.com/a/72408109
concurrency:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
